version: '3'  # version of compose format 

services:
  laptop-service:
    build: ./laptop  
    volumes:
      - ./laptop:/usr/src/app 
    ports:
      - 5001:80  # host:container
    environment:
      - DB_PORT_27017_TCP_ADDR=db
    depends_on:
      - db

  display:
    image: php:apache  
    volumes:
      - ./display:/var/www/html 
    ports:
      - 5000:80  # host:container
    depends_on:
      - laptop-service  # website is not going to work unless laptop-service is running

  web:
    build: ./DockerMongo
    command: python -u flask_brevets.py
    ports:
      - "5002:5000"
    volumes:
      - ./DockerMongo:/app
    environment:
      - DB_PORT_27017_TCP_ADDR=db
    depends_on:
      - db
  db:
    image: mongo